#!/bin/bash

function gen_book
{
    python tool/bookJsonMaker.py $1
    rm -r docs/$1
    cd books/$1
    book sm -s "\d-" -i 準備中
    cd ../../
    python tool/change_summary.py $1
    gitbook build
	rm -r _book/md
    mv _book docs/$1
    rm book.json
}

array=($(ls ./books/))

for i in "${array[@]}"
do
    gen_book $i
done
